[package]
name = "space_shooter"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_asset_loader = "0.22.0"
bevy_ecs = "0.15.3"
bevy_state = "0.15.3"
image = "0.25.6"
rand = "0.9.0"
